### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by loidsemus** [NiklasEi/LMGTFY#1] opened 2017-12-19 18:54 UTC
"split(File.separator)[0]" on line 39 in FileUtil class is causing errors on startup every time;

PatternSyntaxException: Unexpected internal error near index 1:

at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_91]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_91]
        at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_91]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_91]
        at java.lang.String.split(Unknown Source) ~[?:1.8.0_91]
        at java.lang.String.split(Unknown Source) ~[?:1.8.0_91]
        at me.nikl.lmgtfy.util.FileUtil.copyDefaultLanguageFiles(FileUtil.java:38) ~[?:?]
        at me.nikl.lmgtfy.Main.reload(Main.java:40) ~[?:?]
        at me.nikl.lmgtfy.Main.onEnable(Main.java:24) ~[?:?]

I've tried to fix this with no success :/

**Comment by NiklasEi** [comment] 2017-12-20 03:23
Please verify, but it should be fixed in 0aa80180a8d57d1e29f005658e0e06bc72fd6302.

This was caused by the file separator char on Windows, that has to be escaped in a regex.

**Closed as completed** 2017-12-20 11:55 UTC
